apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-service
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: {{ .Values.deployment.port }}
    targetPort: {{ .Values.deployment.port }}
  selector:
    app: {{ .Values.deployment.name }}