apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.deployment.docker.secret }}
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.docker.image}}:{{$.Values.deployment.docker.tag}}
        ports:
        - containerPort: {{ .Values.deployment.port }}
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.secret }}
              key: DB_USER
              optional: false
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.secret }}
              key: DB_PASSWORD
              optional: false
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {{ .Values.database.secret }}
              key: DB_NAME
              optional: false
        - name: DB_PORT
          value: "{{ .Values.database.port }}"
        - name: DB_HOST
          value: "{{ .Values.database.host }}"
        - name: APP_PORT
          value: "{{ .Values.deployment.port }}"
