apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-service
spec:
  type: ExternalName
  externalName: {{ .Values.deployment.name }}-service
  ports:
    - port: 8086
      name: http