apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
data:
  config.yaml: |
  otel-collector-config: |
    receivers:
      otlp:
        protocols:
          http:
            endpoint: "0.0.0.0:4317"

    processors:
      batch:

    exporters:
      logging:
        loglevel: debug

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [logging]
