apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector:latest
        ports:
        - containerPort: 4317 # OTLP gRPC port
        - containerPort: 4318 # OTLP HTTP port
        volumeMounts:
        - name: config-volume
          mountPath: /etc/otel-collector-config
          readOnly: true
        args: ["--config", "/etc/otel-collector-config/config.yaml"]
        resources:
          limits:
            memory: "200Mi"
            cpu: "500m"
          requests:
            memory: "100Mi"
            cpu: "250m"
      volumes:
      - name: config-volume
        configMap:
          name: otel-collector-config
