apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{$.Values.deployment.name}}
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{$.Values.deployment.name}}
            image: {{$.Values.deployment.image.path}}:{{$.Values.deployment.image.tag}}
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure