deployment:
  name: lurnen-db-api
  docker:
    image: artemek47/lurnen-db-api
    tag: latest
    secret: docker.secret
  resources:
    cpu: 100m
    memory: 250Mi
  port: 8080
  repllicas: 1
database:
  secret: postgres-creds
  host: postgres-db-service
  port: 5432
