apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  storageClassName: STORAGE_CLASS_NAME_VAR
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi