deployment:
  name: lurnen
  domain: lurnen.com
  docker:
    image: artemek47/smartsforall
    tag: latest
    secret: docker.secret
  resources:
    cpu: 100m
    memory: 250Mi
  port: 80
  repllicas: 1