apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{$.Values.deployment.name}}
spec:
  schedule: {{$.Values.deployment.schedule | quote }}
  suspend: {{$.Values.deployment.suspend}}
  succesfulJobsHistoryLImit: 3
  failedJobsHistoryLimit: 1
  startingDeadlineSeconds: 300
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{$.Values.deployment.name}}
            image: {{$.Values.deployment.docker.image}}:{{$.Values.deployment.docker.tag}}
            imagePullPolicy: Always
            resources:
              limits:
                cpu: {{$.Values.deployment.resources.cpu}}
                memory: {{$.Values.deployment.resources.memory}}
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: {{$.Values.deployment.docker.secret}}