# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v4

      # - name: Authenticate Kubernetes
      #   uses: actions-hub/kubectl@master
      #   env:
      #     KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      #   with:
      #     args: get pods

      - name: Set up Kubeconfig
        env:
          KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "${KUBECONFIG}" > ~/.kube/config

      - name: Install kubectl
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl

      - run: kubectl get pods
          
      - name: pull kubeconfig
        run: |
          mkdir kubeconf
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconf/kubeconf.conf

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
  
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: 'latest'

      - name: Uninstall Previous Deployment
        run: helm uninstall smartsforall

      - name: Install Deployment
        if: always()
        run: helm upgrade --install smartsforall smartsforall/charts
  
      # - name: Helm Upgrade
      #   run: |
      #     helm upgrade my-release my-chart-repo/my-chart \
      #       --namespace my-namespace \
      #       --set image.tag=${{ github.sha }}